name: CI

on:
  push:
    branches:
      - main
      - release*
  pull_request_target: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Check formatting
        run: npm run format-check
      - name: Build
        run: npm run build --if-present
      - name: Package artifacts
        run: npm run package
      - name: Run Tests
        run: npm run test-verbose
        env:
          CI: true
      - name: Publish artifacts
        if: >
          github.ref == 'refs/heads/main'
            || contains('refs/heads/release', github.ref)
        uses: EndBug/add-and-commit@v9
        with:
          commit: --signoff
          default_author: github_actions
          fetch: false
          message: 'dist: build new artifacts'
          push: true