name: Release next preview
on:
  push:
    branches:
      - main
jobs:
  move-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create and move next-preview tag
        run: |
          git tag v1.next-preview --force
          git push origin v1.next-preview --force
